### ISSUE TITLE
Saving filter state

### ISSUE THREAD

**Issue by AmanRaj1608** [dracula/draculatheme.com#106]
On refresh or changing to the different pages, we lose the filter state. 

We can use `localstorage` to save filter state so that even after refreshing or coming back from different app pages we are still viewing what we had chosen.

![](https://media.giphy.com/media/hWw9kHXNXMrvreSzb4/giphy.gif)

**Comment by zenorocha** [comment]
That's a great addition. I just merged and deployed your last pull request.

Would you mind sending another pull request to save the input search state as well?

**Comment by AmanRaj1608** [comment]
@zenorocha 

Sure I'm on it.

**Comment by AmanRaj1608** [comment]
@zenorocha It's done. Please review.
