### ISSUE TITLE
Malarkey text not being reset on page load

### ISSUE THREAD

**Issue by deadmeu** [dracula/draculatheme.com#113]
From the home page, if you click the "Dracula" link in the top let corner a few times, the "Dark theme for ..." Malarkey rotating subheading will append app name values:
![text-overflow](https://user-images.githubusercontent.com/12111013/92989150-9ee69b00-f4c1-11ea-88b0-fba49cf20e7c.gif)

**Comment by wasi-master** [comment]
Weird issue. I'd love to know what causes this

**Comment by zenorocha** [comment]
@wasi-master the biggest issue here was the `componentDidUpdate` piece

**Comment by zenorocha** [comment]
Thanks a lot @deadmeu, it took forever but it's finally fixed.

**Comment by wasi-master** [comment]
Oh, thanks for the information

**Comment by deadmeu** [comment]
> Thanks a lot @deadmeu, it took forever but it's finally fixed.

Great work! I had a look myself but couldn't figure it out, glad you found it :slightly_smiling_face:

**Comment by gdcmarinho** [comment]
We can close this issue, @zenorocha.

**Comment by luxonauta** [comment]
Thank you all for the feedback and help! 😊
