### ISSUE TITLE
Trigger update when a repository changes

### ISSUE THREAD

**Issue by alexherbo2** [dracula/draculatheme.com#115]
Hi @zenorocha,

I updated the [dracula/kakoune] repository to add transparency support, but I do not see the changes in the [draculatheme.com/kakoune] page.

[dracula/kakoune]: https://github.com/dracula/kakoune
[draculatheme.com/kakoune]: https://draculatheme.com/kakoune

**Comment by zenorocha** [comment]
I agree we need to automate this @alexherbo2. Today I'm using Vercel to deploy the site, so if someone could send a GitHub Action that makes that possible, it would be great.

**Comment by zenorocha** [comment]
This has been addressed.
