### ISSUE TITLE
add the hugo theme on the website

### ISSUE THREAD

**Issue by chrisbeardy** [dracula/draculatheme.com#116]
https://themes.gohugo.io/hugo-piercer-theme/

**Comment by luxonauta** [comment]
Hi @chrisbeardy 👋🏻, you can open this Issue in this [repository](https://github.com/dracula/dracula-theme). There is the best place!
Here's the [template](https://github.com/dracula/template) if you want to try writing the theme installation instructions. 😊

**Comment by sionta** [comment]
Hy @luxonauta,i would like to contribute to this, is it possible?

**Comment by luxonauta** [comment]
Yeah, for sure! I would recommend the following: https://draculatheme.com/contribute 😊
