### ISSUE TITLE
add Joplin theme on website

### ISSUE THREAD

**Issue by chrisbeardy** [dracula/draculatheme.com#117]
https://github.com/laurent22/joplin/pull/1924

The theme is now selectable via the dropdown.

![image](https://user-images.githubusercontent.com/20585410/95886120-13894f80-0d76-11eb-819a-d7353a665d9b.png)

**Comment by zenorocha** [comment]
https://draculatheme.com/joplin 🎉

**Comment by zenorocha** [comment]
thanks @chrisbeardy for letting us know!
