### ISSUE TITLE
Add Monkeytype

### ISSUE THREAD

**Issue by zenorocha** [dracula/draculatheme.com#122]
> Suggested by Alexander Atsales

<img width="1791" alt="Screen Shot 2021-01-17 at 12 13 19 AM" src="https://user-images.githubusercontent.com/398893/104835074-e3f85080-5858-11eb-9bf8-db7b22ffc885.png">

**Comment by UnrealApex** [comment]
https://github.com/UnrealApex/monkeytype

**Comment by zenorocha** [comment]
https://draculatheme.com/monkeytype 💥
