### ISSUE TITLE
Arrow character does not render in powershell installation instructions

### ISSUE THREAD

**Issue by benj2240** [dracula/draculatheme.com#125]
## Symptom
On https://draculatheme.com/powershell/, under "Theme Installation", under "Windows Titlebar Color", there are several Rightwards Arrow characters ([U+2192](https://www.compart.com/en/unicode/U+2192)). For me, in Firefox, they show as a lowercase "b". In Edge, they show as a lowercase "b" followed by two boxes. Screenshot of Edge below.

## Screenshots
The installation instructions on GitHub (https://github.com/dracula/powershell/blob/master/INSTALL.md):
![Screenshot of install.md ](https://user-images.githubusercontent.com/1518282/109574373-0367d780-7aad-11eb-861b-5543a051e5ca.png)

The installation instructions on draculatheme.com (in Edge):
![Screenshot of the issue in Edge](https://user-images.githubusercontent.com/1518282/109570562-72423200-7aa7-11eb-8e38-226118af045a.png)

The HTML I get from draculatheme.com (inspected with Firefox):
![Screenshot of network traffic](https://user-images.githubusercontent.com/1518282/109572880-3e690b80-7aab-11eb-957f-ae5dd20e2b27.png)

## Details
From what I can tell, these instructions are fetched from GitHub using an API call: `https://api.github.com/repos/dracula/powershell/contents/INSTALL.md`. For me that API call returns the correct data, in which the arrow character is UTF-8 encoded as `0xE28692`.

When I visit https://draculatheme.com/powershell/, it seems the character has been replaced with `0x620612`. The `0x62` explains why I'm seeing a "b".

## Speculation
I will hazard a guess that the issue is due to this line, which attempts to treat install.md as ASCII:
https://github.com/dracula/draculatheme.com/blob/712930738c9f234ad5ca65dc864d133743f3fd59/pages/%5Btheme%5D.js#L27

If the restriction to ASCII is intentional, then the fix may be to update that markdown file to replace the arrows with, perhaps, `>`.

If the restriction to ASCII is unintentional, then the fix may be to use `installBuffer.toString('utf8')` instead.

**Comment by zenorocha** [comment]
That's amazing! Thank you so much for doing that deep investigation, you were totally right @benj2240 :)
