### ISSUE TITLE
Add link to github repo for the current app's theme?

### ISSUE THREAD

**Issue by redxtech** [dracula/draculatheme.com#136]
Would it be possible to add a link to the current app's github repo?

For example the vim theme page would include a link to dracula/vim.

You currently have to click on the github org, and search for the app's repo.

I could make a PR, let me know where you'd like it.

**Comment by zenorocha** [comment]
Another user complained about the same thing today on Discord:
https://discord.com/channels/820858204472213505/849860816114941983/934125648614678568

So we might need to revisit that's page design in order to improve it.

Thanks @redxtech for reporting!

**Comment by wasi-master** [comment]
Doesn't this hyperlink work?

![image](https://user-images.githubusercontent.com/63045920/151652133-10f25a3d-18b2-4013-8902-b3bcaf61c24a.png)

**Comment by redxtech** [comment]
> Doesn't this hyperlink work?
> 
> ![image](https://user-images.githubusercontent.com/63045920/151652133-10f25a3d-18b2-4013-8902-b3bcaf61c24a.png)

I'm going to be completely honest, I didn't even notice that link. It's possible I thought it would just go to the main dracula repository, as with the other GitHub links on the pages.

Is it possible to move the link to somewhere more obvious on the page?

**Comment by wasi-master** [comment]
Yeah moving that link to somewhere more obvious would be nicer

**Comment by zenorocha** [comment]
I believe a 2-column layout might help with this. The npm website and VSCode Marketplace are good examples of that:

![image](https://user-images.githubusercontent.com/398893/152096660-7df7cb85-233a-4b05-9a0a-5bfc51f060a7.png)

**Comment by wasi-master** [comment]
Yeah that would be very good

**Comment by redxtech** [comment]
I agree, that would definitely make it obvious where to find the repo.

**Comment by luxonauta** [comment]
Hi 👋🏻, It's been a while; I believe [this PR](https://github.com/dracula/draculatheme.com/pull/160), has solved this Issue. 😅
We created a link that will redirect to the repository:

![image](https://user-images.githubusercontent.com/48334856/181345727-66b86eed-0d93-4c3c-b9f2-c73d39e3db0a.png)

So I'll be closing this Issue! Thanks, everyone, for the feedback! ❤️
