### ISSUE TITLE
npm ERR! 404 Not Found - GET https://registry.npmjs.org/dracula-ui - Not found

### ISSUE THREAD

**Issue by cchacons** [dracula/draculatheme.com#144]
Anyone experiencing this error when running npm install or npm i dracula-ui?

```
npm i dracula-ui
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/dracula-ui - Not found
npm ERR! 404 
npm ERR! 404  'dracula-ui@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cchacon/.npm/_logs/2022-01-19T16_12_36_488Z-debug.log

```

**Comment by zenorocha** [comment]
This is happening because dracula-ui is a private package and requires a GitHub Access Token to download it.

I'm sorry about that. This is a pretty big limitation for open source contribution, and I'll think about ideas on how to fix it.

**Comment by colintoh** [comment]
I having the error too. I paid for the Dracula UI, created .npmrc with the personal token. Still gives me the same error.

**Comment by luxonauta** [comment]
Hi @colintoh 👋🏻! As stated above, Dracula UI uses GitHub Packages to distribute the code for you. 😅

There is an [installation guide](https://ui.draculatheme.com/installation) in the [documentation](https://ui.draculatheme.com/). It is essential that you first create a GitHub Personal Access Token with the following scopes: `write:packages` and `delete:packages`.

You can also seek help on [Dracula's Discord](https://draculatheme.com/discord-invite)! 😊
