### ISSUE TITLE
Nested lists don't seem to work properly

### ISSUE THREAD

**Issue by wasi-master** [dracula/draculatheme.com#151]
On [draculatheme.com/codeblocks](https://draculatheme.com/codeblocks):
![image](https://user-images.githubusercontent.com/63045920/151651064-4b90b837-2a1f-44db-bea9-d772e8558c6b.png)

On [github.com/dracula/codeblocks](https://github.com/dracula/codeblocks/blob/master/INSTALL.md):
![image](https://user-images.githubusercontent.com/63045920/151651091-e048ea48-180a-4f61-9326-5a4517075273.png)

One thing I think may be the cause is me using 2 spaces for indentation. I switched them to 4 but I don't think the website got updated.

**Comment by wasi-master** [comment]
Oh and I'm just noticing another thing, keyboard tags (`<kbd>`) also don't work

**Comment by zenorocha** [comment]
https://github.com/dracula/draculatheme.com/pull/155
