### ISSUE TITLE
Gradients and colors seems broken on https://draculatheme.com/ui

### ISSUE THREAD

**Issue by Go-Merk** [dracula/draculatheme.com#163]
![image](https://user-images.githubusercontent.com/54755295/157098897-d3f8bf37-7bd4-4fa9-929c-f43f8bd1cecd.png)
![image](https://user-images.githubusercontent.com/54755295/157098996-34507bb3-38ad-444a-b77c-9ebe8294dc3a.png)
![image](https://user-images.githubusercontent.com/54755295/157099359-f3dd75fc-8ab5-429a-8377-d302302d9367.png)

pics from my phone and notebook.

**Comment by zenorocha** [comment]
Fixed now, thanks a lot @Go-Merk !
