### ISSUE TITLE
Getting `Application error` whenever viewing package pages

### ISSUE THREAD

**Issue by hwittenborn** [dracula/draculatheme.com#178]
I'm getting the error on `/iterm` and `/gtk` at the least, thought all routes appear to be affected.

This is the error I see:

![image](https://user-images.githubusercontent.com/74838472/178191942-afc04ffc-4d8c-44a8-897d-918736f78778.png)

And the Console log:

![image](https://user-images.githubusercontent.com/74838472/178192009-c5e4aefb-78b3-4538-bf76-f645623aad36.png)

I'm on Firefox 102.0 on Kubuntu 22.04.

**Comment by zenorocha** [comment]
This should be fixed now, thanks for letting me know!
