### ISSUE TITLE
Shop Cart Links Not Working

### ISSUE THREAD

**Issue by kr1st1nagr03g3r** [dracula/draculatheme.com#197]
Hello, there.

I was trying to purchase some stickers and a t-shirt and realized that the linking doesn't work on https://draculatheme.com/shop/.

**Steps to reproduce:**
1. Navigate to: https://draculatheme.com/shop
2. Select [ASCII Shirt](https://draculatheme.com/shop/ascii-shirt)
3. Select size and quantity and click on Add to cart.
4. Result ends up at Gumroad checkout popup which mentions "you haven't added anything yet!". (See Image)

![image](https://user-images.githubusercontent.com/94015887/194406016-b052f369-571f-4c63-9390-9b0d75b12f64.png)

**Expected Result:**
(Steps 1-3 above)
4. End up at this url: https://draculatheme.gumroad.com/l/ascii-shirt

I noticed the same for the [Dracula Sticker Pack](https://draculatheme.gumroad.com/l/dracula-sticker-pack), and come to mention it the rest of the products. Would love to contribute to same to fix. Thanks for the cool theme!

**Comment by luxonauta** [comment]
Hi 👋🏻, it looks like the bug has already been fixed; thank you very much for reporting it! 🦇
