### ISSUE TITLE
Menu mobile in desktop version

### ISSUE THREAD

**Issue by bruno88cabral** [dracula/draculatheme.com#228]
![image](https://user-images.githubusercontent.com/19210426/210417122-f01de75c-ccac-4516-a832-ab9ed77ba30a.png)

I'm using a notebook with a 14 inch screen and 1600 x 900 pixels.

**Comment by luxonauta** [comment]
Hi 👋🏻 Bruno; thank you very much for your interest in providing this feedback. ✨

🧛🏻‍♂️ But there is a better place to share the same, which is the [project repository](https://github.com/dracula/dracula-ui); here, we only concentrate on issues from the **Dracula Theme**, **Dracula PRO**, and the **store website**.

✅ By [clicking here](https://github.com/dracula/dracula-ui/issues/new), you can open an Issue there.

Also, I have yet to be able to replicate the issue 😅, but we can discuss it more over there in the [Dracula UI repo](https://github.com/dracula/dracula-ui).
