### ISSUE TITLE
View counters seem to be frozen

### ISSUE THREAD

**Issue by mrhappyma** [dracula/draculatheme.com#246]
The view counters on the site seem to be frozen. A number of themes, including [the replugged theme](https://draculatheme.com/replugged) are stuck at 0 views, and I haven't been keeping track but I think the other ones haven't changed in a while too.

**Comment by luxonauta** [comment]
✅ Thanks for reporting; we are already working on it!

**Comment by mrhappyma** [comment]
This still seems to be an issue. Can you reopen this issue?

**Comment by mrhappyma** [comment]
@luxonauta this is still an issue

**Comment by luxonauta** [comment]
Yes, it is known to us on the team, and we are working on a migration, so it still needs to be fixed. 😅
