### ISSUE TITLE
Updates Atom page to include UI theme

### ISSUE THREAD

**Issue by zenorocha** [dracula/draculatheme.com#25]
https://github.com/dracula/atom-ui

**Comment by bigpick** [comment]
Per the Atom Dracula page;

> Install using Atom. 
>   * Go to Atom -> Preferences...  
>   * Then select the Install tab. 
>   * Click the Themes button to the right of the search box 
>   * **Enter dracula-ui in the search box**  

This seems to already be in place. Maybe should also include installing the **Dracula Syntax** though?
