### ISSUE TITLE
Useless scrollbar?

### ISSUE THREAD

**Issue by Subtixx** [dracula/draculatheme.com#256]
On the color palette there is a scrollbar for 1-10px:
![image](https://github.com/dracula/draculatheme.com/assets/20743379/ec8d1b9a-b622-4156-b696-768c5e648dc0)

![image](https://github.com/dracula/draculatheme.com/assets/20743379/f88c3973-e2e5-4e7c-bd15-c2201326bd53)

**Comment by luxonauta** [comment]
Fixed in https://github.com/dracula/draculatheme.com/commit/7c7baf896f332e54ede6d77f02286c3a9f4453aa
