### ISSUE TITLE
Tailwind CSS

### ISSUE THREAD

**Issue by chris-nowicki** [dracula/draculatheme.com#262]
Hello!  I'd love to help out and contribute where needed!  I saw on GitHub y'all were thinking about moving to Tailwindcss and I'd love to help here if I can or any other area.  I am a huge fan of NextJS and Tailwind.

**Comment by luxonauta** [comment]
Although it is not a priority, we intend to migrate by next year. 😁

I'm going to list here some things we want to improve that would be great to have an extra hand on:

- We want to improve the general performance further, but mainly on the home page;
- SEO;
- Create sections such as: "People also like" for themes and blog posts;
- Create a categorization on the blog page;
- In blog posts, have a "table-of-contents" and, at the end, a section: "Share this post".

I primarily developed and designed the website, so let me know if you need any help! 🧛🏻
