### ISSUE TITLE
Polybar page links to wrong repo

### ISSUE THREAD

**Issue by tomovicj** [dracula/draculatheme.com#272]
https://draculatheme.com/polybar links to [matheusortiz/dracula-polybar](https://github.com/matheusortiz/dracula-polybar) instead of [dracula/polybar](https://github.com/dracula/polybar).

**Comment by jrdnbradford** [comment]
This is an issue with [dracula/polybar](https://github.com/dracula/polybar) and should be fixed when https://github.com/dracula/polybar/pull/1 is merged.
